# Generated by Django 4.2.5 on 2023-09-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_teacher",
            field=models.BooleanField(default=False, verbose_name="Teacher"),
        ),
    ]
