# Generated by Django 4.2.5 on 2023-10-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_choice_mcquestion_quiz_quizattempt_mcquestion_quiz_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizattempt",
            name="question",
        ),
        migrations.RemoveField(
            model_name="quizattempt",
            name="selected_choice",
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="selected_choices",
            field=models.ManyToManyField(to="users.choice"),
        ),
    ]
