# Generated by Django 4.2.5 on 2023-10-02 19:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_quizattempt_question_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mcquestion",
            name="text",
        ),
    ]
