# Generated by Django 4.2.5 on 2023-10-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_remove_mcquestion_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcquestion",
            name="text",
            field=models.TextField(null=True),
        ),
    ]
