# Generated by Django 4.2.5 on 2023-10-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DiscussionBoard", "0002_reply"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="file_upload",
            field=models.FileField(
                blank=True, null=True, upload_to="questions_uploads/"
            ),
        ),
        migrations.AddField(
            model_name="reply",
            name="file_upload",
            field=models.FileField(blank=True, null=True, upload_to="replies_uploads/"),
        ),
    ]
