# Generated by Django 4.2.5 on 2023-10-02 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("DiscussionBoard", "0003_question_file_upload_reply_file_upload"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="file_upload",
        ),
        migrations.RemoveField(
            model_name="reply",
            name="file_upload",
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="attachments/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="DiscussionBoard.question",
                    ),
                ),
                (
                    "reply",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="DiscussionBoard.reply",
                    ),
                ),
            ],
        ),
    ]
