# Generated by Django 4.2.5 on 2023-10-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "DiscussionBoard",
            "0004_remove_question_file_upload_remove_reply_file_upload_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Visits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("count", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
